export const alunos = [
  { nome: 'Ana', sobrenome: 'Silva', email: 'ana.silva@escola.lab', sexo: 'F', idade: 17, peso: 58.5, altura: 1.62 },
  { nome: 'Bruno', sobrenome: 'Santos', email: 'bruno.santos@escola.lab', sexo: 'M', idade: 18, peso: 72.0, altura: 1.75 },
  { nome: 'Carla', sobrenome: 'Oliveira', email: 'carla.oliveira@escola.lab', sexo: 'F', idade: 16, peso: 54.2, altura: 1.58 },
  { nome: 'Diego', sobrenome: 'Souza', email: 'diego.souza@escola.lab', sexo: 'M', idade: 19, peso: 78.3, altura: 1.8 },
  { nome: 'Elena', sobrenome: 'Costa', email: 'elena.costa@escola.lab', sexo: 'F', idade: 17, peso: 61.0, altura: 1.65 },
  { nome: 'Felipe', sobrenome: 'Lima', email: 'felipe.lima@escola.lab', sexo: 'M', idade: 20, peso: 81.5, altura: 1.82 },
  { nome: 'Gabriela', sobrenome: 'Ferreira', email: 'gabriela.ferreira@escola.lab', sexo: 'F', idade: 18, peso: 59.8, altura: 1.6 },
  { nome: 'Henrique', sobrenome: 'Alves', email: 'henrique.alves@escola.lab', sexo: 'M', idade: 16, peso: 65.0, altura: 1.7 },
  { nome: 'Isabela', sobrenome: 'Ribeiro', email: 'isabela.ribeiro@escola.lab', sexo: 'F', idade: 19, peso: 63.4, altura: 1.68 },
  { nome: 'João', sobrenome: 'Martins', email: 'joao.martins@escola.lab', sexo: 'M', idade: 17, peso: 70.2, altura: 1.73 },
  { nome: 'Larissa', sobrenome: 'Pereira', email: 'larissa.pereira@escola.lab', sexo: 'F', idade: 18, peso: 57.1, altura: 1.63 },
  { nome: 'Marcos', sobrenome: 'Carvalho', email: 'marcos.carvalho@escola.lab', sexo: 'M', idade: 21, peso: 85.0, altura: 1.85 },
  { nome: 'Natália', sobrenome: 'Gomes', email: 'natalia.gomes@escola.lab', sexo: 'F', idade: 16, peso: 52.8, altura: 1.57 },
  { nome: 'Otávio', sobrenome: 'Barbosa', email: 'otavio.barbosa@escola.lab', sexo: 'M', idade: 19, peso: 76.6, altura: 1.78 },
  { nome: 'Patrícia', sobrenome: 'Dias', email: 'patricia.dias@escola.lab', sexo: 'F', idade: 20, peso: 64.5, altura: 1.66 },
  { nome: 'Rafael', sobrenome: 'Nunes', email: 'rafael.nunes@escola.lab', sexo: 'M', idade: 18, peso: 74.1, altura: 1.76 },
  { nome: 'Sofia', sobrenome: 'Mendes', email: 'sofia.mendes@escola.lab', sexo: 'F', idade: 17, peso: 56.3, altura: 1.61 },
  { nome: 'Thiago', sobrenome: 'Rocha', email: 'thiago.rocha@escola.lab', sexo: 'M', idade: 16, peso: 68.9, altura: 1.72 },
  { nome: 'Úrsula', sobrenome: 'Teixeira', email: 'ursula.teixeira@escola.lab', sexo: 'F', idade: 19, peso: 60.7, altura: 1.64 },
  { nome: 'Vinícius', sobrenome: 'Araújo', email: 'vinicius.araujo@escola.lab', sexo: 'M', idade: 18, peso: 73.5, altura: 1.79 },
];
